"""
core.py -- all physics for the interacting Hatano-Nelson model (open and
periodic boundaries): model construction, time evolution, exact and
truncated-Krylov counterdiabatic (CD) driving, and the spectral diagnostics
(adiabatic reference, condition-(17) window) used to build the three figures

    HN_OBC_CD_fig            (data_obc_cd.py     -> plot.py obc_cd)
    HN_PBC_Excess_Energy     (data_pbc_excess.py -> plot.py pbc_excess)
    HN_PBC_CD                (data_pbc_cd.py     -> plot.py pbc_cd)

Model (Eq. 55 of the manuscript), fixed particle number N/2:

    H_HN(h) = (J/2) sum_n [ e^{a h} c^dag_n c_{n+1} + e^{-a h} c^dag_{n+1} c_n ]
              + U sum_n n_n n_{n+1}

with either open bonds (n = 0..N-2) or a periodic wrap bond (n = 0..N-1, mod N).

Open boundaries admit an EXACT adiabatic gauge potential for h,

    A_h = -i a X,        X = sum_n n c^dag_n c_n ,

via the imaginary gauge transform S(h) = exp(-a h X); see `evolve_obc_exact`.
Periodic boundaries have no such closed form (S is not single-valued on a
ring), so the CD term there is built from a truncated Krylov subspace
generated by L = [H, .] acting on d_h H (`agp`, `agp_grid`, `evolve_cd`).

All matrices are dense (D = C(N, N/2), N=10 -> D=252), which is what makes
exact diagonalisation per h-point (needed for the Krylov ground-state
projection and the condition-(17) tracked spectrum) affordable.
"""

import numpy as np
import scipy.sparse as sp
from itertools import combinations
from scipy.linalg import expm
from scipy.optimize import linear_sum_assignment

# ----------------------------------------------------------------------
# Basis and model operators
# ----------------------------------------------------------------------

def basis(N, Np):
    """Fixed-filling occupation-number basis as sorted bitmasks."""
    states = sorted(sum(1 << o for o in occ) for occ in combinations(range(N), Np))
    return states, {s: i for i, s in enumerate(states)}


def _hop(m, i, j):
    """<m'| c^dag_i c_j |m>. Returns (new_state, fermionic_sign) or None.

    The "count fermions below the site" convention gives the correct
    Jordan-Wigner sign for the periodic wrap bond as well as open bonds.
    """
    if not (m >> j) & 1:
        return None
    m1 = m ^ (1 << j)
    s = bin(m & ((1 << j) - 1)).count("1")
    if (m1 >> i) & 1:
        return None
    s += bin(m1 & ((1 << i) - 1)).count("1")
    return m1 | (1 << i), (-1) ** s


def model_operators(N, Np, pbc):
    """
    Precompute the h-independent pieces so H(h) is assembled by scalar
    reweighting:

        H(h) = (J/2) [ e^{a h} T_p + e^{-a h} T_m ] + U V

    Returns T_p, T_m (dense complex, D x D), V (diagonal, real), X (diagonal
    position operator, sites labelled 1..N), D.
    """
    states, idx = basis(N, Np)
    D = len(states)
    T_p = np.zeros((D, D), dtype=complex)   # sum_n c^dag_n c_{n+1}
    T_m = np.zeros((D, D), dtype=complex)   # sum_n c^dag_{n+1} c_n
    V = np.zeros(D)                          # nearest-neighbour interaction
    X = np.zeros(D)                          # position operator
    bonds = [(n, (n + 1) % N) for n in range(N if pbc else N - 1)]

    for col, m in enumerate(states):
        X[col] = sum(n + 1 for n in range(N) if (m >> n) & 1)
        for (i, j) in bonds:
            V[col] += ((m >> i) & 1) * ((m >> j) & 1)
            r = _hop(m, i, j)
            if r is not None:
                T_p[idx[r[0]], col] += r[1]
            r = _hop(m, j, i)
            if r is not None:
                T_m[idx[r[0]], col] += r[1]
    return T_p, T_m, V, X, D


def hamiltonian(h, ops, J=1.0, U=1.0, a=1.0):
    T_p, T_m, V, X, D = ops
    return 0.5 * J * (np.exp(a * h) * T_p + np.exp(-a * h) * T_m) \
        + U * np.diag(V).astype(complex)


def dH(h, ops, J=1.0, U=1.0, a=1.0):
    """d H(h) / d h, needed to seed the Krylov AGP at periodic boundaries."""
    T_p, T_m, V, X, D = ops
    return 0.5 * J * a * (np.exp(a * h) * T_p - np.exp(-a * h) * T_m)


# ----------------------------------------------------------------------
# Generic time evolution (exponential-midpoint propagator, Taylor action)
# ----------------------------------------------------------------------

def _taylor_step(gen, psi, dt, order=16):
    """
    psi <- exp(-i dt gen) psi by truncated Taylor series.

    Chosen over scipy.linalg.expm because we only need the action on a
    vector, which costs `order` matrix-vector products instead of a full
    matrix exponential. order=16 is far beyond convergence for ||gen|| dt <~ 0.5.
    """
    term = psi
    out = psi.copy()
    for k in range(1, order + 1):
        term = (-1j * dt / k) * (gen @ term)
        out = out + term
    return out


def evolve(tau, ops, J=1.0, U=1.0, a=1.0, h0=0.1, dt_target=0.02, max_steps=8000):
    """
    Linear ramp h(t) = h0 t/tau, no CD term, exponential-midpoint propagator.

    The state is renormalised after every step. This is essential at PBC,
    where the norm grows like exp(int Im E dt) and would overflow; it does
    not affect <H>/<psi|psi>, which is all the excess energy needs.
    """
    n_steps = int(np.clip(np.ceil(tau / dt_target), 200, max_steps))
    dt = tau / n_steps
    H0 = hamiltonian(0.0, ops, J, U, a)
    psi = np.linalg.eigh(H0.real)[1][:, 0].astype(complex)
    for k in range(n_steps):
        gen = hamiltonian(h0 * (k + 0.5) / n_steps, ops, J, U, a)
        psi = _taylor_step(gen, psi, dt)
        psi /= np.linalg.norm(psi)
    return psi


# ----------------------------------------------------------------------
# Open boundaries: exact CD term A_h = -i a X
# ----------------------------------------------------------------------

def evolve_obc_exact(tau, ops, use_cd, J=1.0, U=1.0, a=1.0, h0=0.1):
    """
    Exact closed-form propagator for OPEN boundaries and a LINEAR ramp. No
    time stepping. Valid for the bare ramp (use_cd=False) and for the exact
    CD drive (use_cd=True); see the module docstring for A_h.

    Substituting psi = S(h(t)) phi with S = exp(-a h X) into
    i d_t psi = H(h(t)) psi and using d_t S = -a hdot X S, S^{-1} X S = X:

        i d_t phi = ( H(0) + i a hdot X ) phi          (no CD)
        i d_t phi = H(0) phi                           (with CD, the two X
                                                          terms cancel)

    For a linear ramp hdot = h0/tau is constant, so both generators are
    time-independent and the evolution is a single matrix exponential. With
    CD this gives psi(tau) = S(h0) psi_0 e^{-i E_0 tau}, i.e. exactly the
    instantaneous ground state, so the excess energy is zero for every tau.
    """
    T_p, T_m, V, X, D = ops
    H0 = hamiltonian(0.0, ops, J, U, a)
    phi0 = np.linalg.eigh(H0.real)[1][:, 0].astype(complex)
    hdot = h0 / tau
    gen = H0 if use_cd else H0 + 1j * a * hdot * np.diag(X).astype(complex)
    phi = expm(-1j * tau * gen) @ phi0
    return np.exp(-a * h0 * X) * phi          # multiply by S(h0), diagonal


def evolve_obc_stepper(tau, ops, use_cd, J=1.0, U=1.0, a=1.0, h0=0.1,
                       dt_target=0.02):
    """
    General (any ramp, any CD term) time stepper for open boundaries, used
    only to cross-check `evolve_obc_exact` for the linear ramp -- see
    `verify_obc` in data_obc_cd.py. use_cd=True adds the exact generator
    hdot * A_h = -i a hdot X.
    """
    T_p, T_m, V, X, D = ops
    n_steps = max(200, int(np.ceil(tau / dt_target)))
    dt = tau / n_steps
    hdot = h0 / tau
    CD = -1j * a * hdot * np.diag(X).astype(complex) if use_cd else 0.0

    H0 = hamiltonian(0.0, ops, J, U, a)
    psi = np.linalg.eigh(H0.real)[1][:, 0].astype(complex)
    for k in range(n_steps):
        h_mid = h0 * (k + 0.5) / n_steps
        gen = hamiltonian(h_mid, ops, J, U, a)
        if use_cd:
            gen = gen + CD
        psi = _taylor_step(gen, psi, dt)
    return psi


# ----------------------------------------------------------------------
# Reference energies and spectral diagnostics
# ----------------------------------------------------------------------

def adiabatic_reference(ops, h0, J=1.0, U=1.0, a=1.0, n_grid=200):
    """Eigenvalue adiabatically continued from the h=0 ground state up to h0,
    by branch continuation (largest biorthogonal overlap with the previous
    right eigenvector)."""
    hs = np.linspace(0.0, h0, n_grid)
    prev = None
    for h in hs:
        H = hamiltonian(h, ops, J, U, a)
        E, R = np.linalg.eig(H)
        L = np.linalg.inv(R)
        i0 = np.argmin(E.real) if prev is None else np.argmax(np.abs(L @ prev))
        prev = R[:, i0].copy()
    return E[i0]


def imaginary_spread(ops, h0, J=1.0, U=1.0, a=1.0, n_grid=60):
    """max_n Im E_n - min_n Im E_n along the ramp, and I = <spread>_h."""
    hs = np.linspace(0.0, h0, n_grid)
    dI = []
    for h in hs:
        E = np.linalg.eigvals(hamiltonian(h, ops, J, U, a))
        dI.append(E.imag.max() - E.imag.min())
    dI = np.array(dI)
    return hs, dI, np.trapezoid(dI, hs) / h0


def tracked_spectrum(ops, h_max, J=1.0, U=1.0, a=1.0, n_grid=400):
    """
    Return hs and E[k, n]: eigenvalue of branch n at grid point k, with
    branches matched between adjacent h by minimising sum |E_i^{k+1} - E_j^{k}|
    (linear-sum assignment). Branch 0 is relabelled to be the one starting
    from the h=0 ground state.
    """
    hs = np.linspace(0.0, h_max, n_grid)
    E_prev = np.linalg.eigvals(hamiltonian(hs[0], ops, J, U, a))
    order = np.argsort(E_prev.real)          # ground state first at h = 0
    E_prev = E_prev[order]
    out = [E_prev.copy()]
    for h in hs[1:]:
        E_now = np.linalg.eigvals(hamiltonian(h, ops, J, U, a))
        cost = np.abs(E_now[None, :] - E_prev[:, None])
        r, c = linear_sum_assignment(cost)
        E_prev = E_now[c]
        out.append(E_prev.copy())
    return hs, np.array(out)


def condition17(ops, h_max, J=1.0, U=1.0, a=1.0, n_grid=400):
    """
    Eqs. (58)-(59) of the manuscript, referenced to the tracked ground state
    (branch 0):

        mu(h)  = max_n Im(E_n(h) - E_0(h))
        I(h_f) = (1/h_f) int_0^{h_f} mu(h) dh

    so that for a linear ramp Gamma(h_f, tau) = tau I(h_f) and the condition
    W = exp(Gamma) ~ 1 fixes tau_max(h_f) = Gamma_target / I(h_f). Returns
    hs, I(h_f) on the grid, mu(h), and the tracked spectrum E.
    """
    hs, E = tracked_spectrum(ops, h_max, J, U, a, n_grid)
    mu = (E.imag - E.imag[:, [0]]).max(axis=1)         # branch 0 = g.s.
    F = np.concatenate([[0.0], np.cumsum(0.5 * (mu[1:] + mu[:-1]) * np.diff(hs))])
    with np.errstate(divide="ignore", invalid="ignore"):
        I = np.where(hs > 0, F / np.maximum(hs, 1e-30), 0.0)
    return hs, I, mu, E


def tau_max(hs, I, gamma_target=1.0):
    with np.errstate(divide="ignore"):
        return np.where(I > 1e-12, gamma_target / np.maximum(I, 1e-30), np.inf)


def excess_series(ops, h_f, taus, J=1.0, U=1.0, a=1.0, **kw):
    """|E(tau) - E_ad(h_f)| for a bare (no CD) linear ramp 0 -> h_f, via
    `evolve`. Used for both PBC ramps and the OBC reference curve."""
    E_ad = adiabatic_reference(ops, h_f, J, U, a)
    H_f = hamiltonian(h_f, ops, J, U, a)
    out = []
    for t in taus:
        psi = evolve(t, ops, J, U, a, h_f, **kw)
        out.append(np.vdot(psi, H_f @ psi) / np.vdot(psi, psi) - E_ad)
    return np.array(out)


def envelope(t, y, w=2):
    """Local maxima of y over a window of half-width w: the decay/oscillation
    envelope plotted against tau."""
    k = [i for i in range(w, len(y) - w)
         if y[i] == max(y[i - w:i + w + 1])]
    return t[k], y[k]


# ----------------------------------------------------------------------
# Periodic boundaries: truncated-Krylov adiabatic gauge potential
# ----------------------------------------------------------------------
#
# No closed form for A_h exists at periodic boundaries (the imaginary gauge
# S = exp(-a h X) is not single-valued on a ring), so we build
#
#     A^(M) = sum_{k=1..M} alpha_k K_{2k-1}
#
# from the Arnoldi Krylov basis generated by L = [H, .] acting on d_h H, and
# fix the alpha_k by one of several projections (`agp` modes below):
#
#   'mr'            global least squares (GMRES-type):
#                       min_alpha || L(i d_h H) + L^2 A^(M) ||_F
#   'galerkin'      global Galerkin, the square (M x M) version of 'mr'
#   'gs_galerkin'   ground-state Galerkin, Eqs. (F1)-(F3): residual r = Q G |R0> required
#                   orthogonal to the trial vectors t_m = Q o_m |R0>
#   'gs_ls'         ground-state least squares (Petrov-Galerkin / GMRES-type):
#                       min_alpha || Q ( i d_h H + [H, A] ) |R0> ||_2
#   'gs_exact'      ground-state row/column of the EXACT AGP (reference, not
#                   a Krylov truncation)
#
# with G = i d_h H + [H, A], Q = 1 - |R_0><L_0|. The ground state |R0> is
# followed by branch continuation (largest biorthogonal overlap with the
# previously selected right eigenvector), not by argmin Re E at each grid
# point: above h_c the eigenvalues move in the complex plane and argmin Re E
# can hop branches, silently targeting the wrong state.

def _ip(A, B):
    return np.vdot(A, B)          # Tr(A^dag B) for matrices stored as arrays


def arnoldi(H, seed, nstep):
    """Orthonormal Krylov basis for L = [H,.] acting on `seed`, full reortho."""
    L = lambda O: H @ O - O @ H
    b0 = np.sqrt(abs(_ip(seed, seed)))
    K = [seed / b0]
    for n in range(nstep):
        v = L(K[-1])
        for _ in range(2):
            for Kj in K:
                v = v - _ip(Kj, v) * Kj
        nv = np.sqrt(abs(_ip(v, v)))
        if nv < 1e-12:
            break
        K.append(v / nv)
    return K, b0


def gs_pair(H, prev=None):
    """(E, r0, l0, i0) with branch continuation if prev is given."""
    E, R = np.linalg.eig(H)
    Li = np.linalg.inv(R)
    i0 = int(np.argmin(E.real)) if prev is None else int(np.argmax(np.abs(Li @ prev)))
    return E, R[:, i0].copy(), Li[i0, :].copy(), i0


def _solve_square(Mx, rhs):
    """Solve the M x M system, falling back to lstsq on breakdown."""
    try:
        cond = np.linalg.cond(Mx)
        if not np.isfinite(cond) or cond > 1e12:
            raise np.linalg.LinAlgError
        return np.linalg.solve(Mx, rhs), cond
    except np.linalg.LinAlgError:
        al, *_ = np.linalg.lstsq(Mx, rhs, rcond=None)
        return al, np.inf


def agp(h, ops, M, mode, prev=None, J=1.0, U=1.0, a=1.0, info=None):
    """A^(M)(h). Returns (A, r0) so the caller can continue the branch.

    mode='gs_exact' returns the ground-state row/column of the exact AGP
    (no Krylov truncation) as a reference; all other modes build
    A^(M) from the same M-vector Krylov subspace, differing only in how
    alpha is fixed (see the section docstring above).
    """
    H = hamiltonian(h, ops, J, U, a)
    dHh = dH(h, ops, J, U, a).astype(complex)
    L = lambda O: H @ O - O @ H

    if mode == "gs_exact":
        E, R = np.linalg.eig(H)
        Li = np.linalg.inv(R)
        i0 = int(np.argmin(E.real)) if prev is None else int(np.argmax(np.abs(Li @ prev)))
        Mo = Li @ dHh @ R
        d = E - E[i0]
        A = np.zeros_like(Mo)
        for m in range(len(E)):
            if m == i0 or abs(d[m]) < 1e-9:
                continue
            A[m, i0] = -1j * Mo[m, i0] / d[m]
            A[i0, m] = -1j * Mo[i0, m] / (-d[m])
        return R @ A @ Li, R[:, i0].copy()

    K, b0 = arnoldi(H, dHh, 2 * M + 1)
    odd = [K[2 * k + 1] for k in range(min(M, (len(K) - 1) // 2))]
    if not odd:
        return np.zeros_like(H), prev
    Lo = [L(o) for o in odd]

    if mode in ("galerkin", "mr"):
        r0 = prev
        rows = np.stack([L(x).ravel() for x in Lo], axis=1)     # L^2 o_k
        rhs = -(L(1j * dHh)).ravel()
        if mode == "mr":
            al, *_ = np.linalg.lstsq(rows, rhs, rcond=None)
            cond = np.nan
        else:
            V = np.stack([o.ravel() for o in odd], axis=1)
            al, cond = _solve_square(V.conj().T @ rows, V.conj().T @ rhs)
    elif mode in ("gs_galerkin", "gs_ls"):
        E, r0, l0, i0 = gs_pair(H, prev)
        Q = lambda v: v - r0 * (l0 @ v)
        C = np.stack([Q(x @ r0) for x in Lo], axis=1)           # Q L(o_k) R0
        d = -Q(1j * dHh @ r0)
        if mode == "gs_ls":
            al, *_ = np.linalg.lstsq(C, d, rcond=None)
            cond = np.nan
        else:
            T = np.stack([Q(o @ r0) for o in odd], axis=1)      # trial vectors
            al, cond = _solve_square(T.conj().T @ C, T.conj().T @ d)
    else:
        raise ValueError(mode)

    if info is not None:
        info.append((h, np.abs(al).copy(), cond))
    return sum(al[k] * odd[k] for k in range(len(odd))), r0


def agp_grid(ops, h_f, M, mode, n_grid=100, verbose=False, **kw):
    hs = np.linspace(0.0, h_f, n_grid)
    prev, out, info = None, [], []
    for h in hs:
        A, prev = agp(h, ops, M, mode, prev=prev, info=info, **kw)
        out.append(A)
    if verbose and info:
        al0, alf = info[0][1], info[-1][1]
        conds = [c for _, _, c in info if np.isfinite(c)]
        print(f"      alpha(h=0) = {np.round(al0, 4)}   "
              f"alpha(h_f) = {np.round(alf, 4)}"
              + (f"   max cond = {max(conds):.2e}" if conds else ""))
    return hs, np.array(out)


def evolve_cd(tau, ops, h_f, hs=None, Ag=None, J=1.0, U=1.0, a=1.0,
              dt_target=0.04, max_steps=20000):
    """
    Linear ramp 0 -> h_f (periodic boundaries). Generator H(h) + hdot A^(M)(h),
    with A interpolated linearly on the precomputed grid (hs, Ag). hs=None
    gives the bare ramp. The state is renormalised each step.
    """
    n_steps = int(np.clip(np.ceil(tau / dt_target), 200, max_steps))
    dt = tau / n_steps
    hdot = h_f / tau
    psi = np.linalg.eigh(hamiltonian(0.0, ops, J, U, a).real)[1][:, 0].astype(complex)
    for k in range(n_steps):
        h = h_f * (k + 0.5) / n_steps
        gen = hamiltonian(h, ops, J, U, a)
        if hs is not None:
            j = np.clip(np.searchsorted(hs, h) - 1, 0, len(hs) - 2)
            w = (h - hs[j]) / (hs[j + 1] - hs[j])
            gen = gen + hdot * ((1 - w) * Ag[j] + w * Ag[j + 1])
        psi = _taylor_step(gen, psi, dt)
        psi /= np.linalg.norm(psi)
    return psi


def excess_series_cd(ops, h_f, taus, hs=None, Ag=None, J=1.0, U=1.0, a=1.0,
                     E_ad=None, **kw):
    """Excess energy along `evolve_cd`, optionally with the CD term (hs, Ag)."""
    if E_ad is None:
        E_ad = adiabatic_reference(ops, h_f, J, U, a)
    H_f = hamiltonian(h_f, ops, J, U, a)
    out = []
    for t in taus:
        psi = evolve_cd(t, ops, h_f, hs, Ag, J, U, a, **kw)
        out.append(np.vdot(psi, H_f @ psi) / np.vdot(psi, psi) - E_ad)
    return np.array(out)


def residual_table(ops, h, Ms=(1, 2, 3, 4, 5),
                   modes=("galerkin", "mr", "gs_galerkin", "gs_ls"), **kw):
    """Diagnostic: ||L G|| and ||Q G R0|| (global and ground-state residual
    of G = i d_h H + [H, A^(M)]) versus M, for orientation when choosing a
    truncation mode."""
    H = hamiltonian(h, ops, **kw)
    dHh = dH(h, ops, **kw).astype(complex)
    L = lambda O: H @ O - O @ H
    E, r0, l0, i0 = gs_pair(H)
    Q = lambda v: v - r0 * (l0 @ v)
    ref_g = np.linalg.norm(L(1j * dHh))
    ref_s = np.linalg.norm(Q(1j * dHh @ r0))
    print(f"  h = {h}   (||L(i dH)|| = {ref_g:.4g}, "
          f"||Q i dH R0|| = {ref_s:.4g})")
    print(f"  {'mode':13s} {'M':>2s}  {'||LG||/ref':>11s} "
          f"{'||QG R0||/ref':>13s} {'||A||_F':>9s}")
    res = {}
    for mode in modes:
        for M in Ms:
            A, _ = agp(h, ops, M, mode, prev=r0, **kw)
            G = 1j * dHh + (H @ A - A @ H)
            rg = np.linalg.norm(L(G)) / ref_g
            rs = np.linalg.norm(Q(G @ r0)) / ref_s
            res[(mode, M)] = (rg, rs, np.linalg.norm(A))
            print(f"  {mode:13s} {M:2d}  {rg:11.4f} {rs:13.4f} "
                  f"{np.linalg.norm(A):9.3f}")
    return res


# ----------------------------------------------------------------------
# Sparse fast propagator, used only to locate the bare-ramp oscillation
# maxima cheaply (Step 1 of data_pbc_cd.py) -- no CD, no dense H assembly.
# ----------------------------------------------------------------------

def sparse_ops(ops, J=1.0, U=1.0, a=1.0):
    T_p, T_m, V, X, D = ops
    return (sp.csr_matrix(T_p), sp.csr_matrix(T_m), U * V.astype(complex),
            0.5 * J, a, D)


def evolve_fast(tau, sops, h_f, dt_target=0.15, order=16, max_steps=200000):
    """Linear ramp 0 -> h_f, no control, sparse matvecs. Returns the final
    (normalised) state."""
    Tp, Tm, Ud, half_J, a, D = sops
    n_steps = int(np.clip(np.ceil(tau / dt_target), 200, max_steps))
    dt = tau / n_steps
    H0 = half_J * (Tp + Tm).toarray().real + np.diag(Ud.real)
    psi = np.linalg.eigh(H0)[1][:, 0].astype(complex)
    for k in range(n_steps):
        h = h_f * (k + 0.5) / n_steps
        cp, cm = half_J * np.exp(a * h), half_J * np.exp(-a * h)
        term = psi
        out = psi.copy()
        for j in range(1, order + 1):
            term = (-1j * dt / j) * (cp * (Tp @ term) + cm * (Tm @ term)
                                     + Ud * term)
            out = out + term
        psi = out / np.linalg.norm(out)
    return psi


def excess_fast(tau, sops, H_f, E_ad, h_f, **kw):
    psi = evolve_fast(tau, sops, h_f, **kw)
    return np.vdot(psi, H_f @ psi) / np.vdot(psi, psi) - E_ad
